# Generated by Django 3.1.3 on 2021-08-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='voice',
        ),
    ]
