# Generated by Django 3.1.3 on 2021-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0002_remove_movie_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='voices',
            field=models.ManyToManyField(to='movie_core.Voice'),
        ),
    ]
