# Generated by Django 3.2.8 on 2021-11-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0002_alter_movie_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='collection',
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_core.movie'),
        ),
    ]
