# Generated by Django 3.2.8 on 2021-11-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0004_auto_20211106_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecollection',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='movie', to='movie_core.Movie'),
        ),
    ]
