# Generated by Django 3.1.3 on 2021-08-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0004_auto_20210816_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='./videos/movies'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='video',
            field=models.FileField(upload_to='./videos/trailers'),
        ),
    ]
