# Generated by Django 3.1.3 on 2021-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0005_auto_20210816_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='banner_image',
            field=models.ImageField(upload_to='images/banner_image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(upload_to='images/cover_image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='videos/movies'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='banner_image',
            field=models.ImageField(upload_to='images/trailers/banner_image'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='cover_image',
            field=models.ImageField(upload_to='images/trailers/cover_image'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='video',
            field=models.FileField(upload_to='videos/trailers'),
        ),
    ]
