# Generated by Django 3.2.8 on 2021-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0005_alter_moviecollection_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecollection',
            name='image',
            field=models.ImageField(null=True, upload_to='images/movies/collections'),
        ),
    ]
