# Generated by Django 3.2.8 on 2021-11-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0006_moviecollection_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name_plural': ' მსახიობები'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': ' კომენტარები'},
        ),
        migrations.AlterModelOptions(
            name='countrie',
            options={'verbose_name_plural': ' ქვეყნები'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': ' რეჟისორები'},
        ),
        migrations.AlterModelOptions(
            name='genrie',
            options={'verbose_name_plural': ' ჟანრი'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': ' ფილმები'},
        ),
        migrations.AlterModelOptions(
            name='moviecollection',
            options={'verbose_name_plural': ' კოლექციები'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': ' პროფილები'},
        ),
        migrations.AlterModelOptions(
            name='voice',
            options={'verbose_name_plural': ' გახმოვანება'},
        ),
    ]
