# Generated by Django 3.1.3 on 2021-08-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0007_auto_20210816_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_image',
            field=models.ImageField(upload_to='images/actors'),
        ),
    ]
