# Generated by Django 3.1.3 on 2021-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0010_auto_20210817_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(),
        ),
    ]
