# Generated by Django 3.1.3 on 2021-08-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0011_auto_20210817_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='director',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='date',
            field=models.DateField(),
        ),
    ]
