# Generated by Django 3.1.3 on 2021-08-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0012_auto_20210817_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
        migrations.AlterField(
            model_name='trailer',
            name='title_geo',
            field=models.SlugField(),
        ),
    ]
