# Generated by Django 3.1.3 on 2021-08-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0013_auto_20210818_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_core.director'),
            preserve_default=False,
        ),
    ]
