# Generated by Django 3.1.3 on 2021-08-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0015_movie_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='type',
            new_name='სახეობა',
        ),
    ]
