# Generated by Django 3.1.3 on 2021-08-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0016_auto_20210818_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='სახეობა',
            new_name='type',
        ),
    ]
