# Generated by Django 3.1.3 on 2021-08-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0025_auto_20210822_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.IntegerField(choices=[('', 'None'), ('ფილმი', 'ფილმი'), ('სერიალი', 'სერიალი'), ('თრეილერი', 'თრეილერი')], default=1),
        ),
    ]
