# Generated by Django 3.1.3 on 2021-08-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0032_auto_20210825_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('ფილმი', 'ფილმი'), ('სერიალი', 'სერიალი'), ('თრეილერი', 'თრეილერი')], max_length=20),
        ),
    ]
