# Generated by Django 3.1.3 on 2021-08-25 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0033_auto_20210825_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='type',
            field=models.CharField(choices=[('ფილმი', 'ფილმი'), ('სერიალი', 'სერიალი'), ('თრეილერი', 'თრეილერი')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
