# Generated by Django 3.1.3 on 2021-09-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0034_trailer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_geo',
            field=models.SlugField(),
        ),
    ]
