# Generated by Django 3.2.7 on 2021-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0035_auto_20210903_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_geo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='title_geo',
            field=models.CharField(max_length=50),
        ),
    ]
