# Generated by Django 3.2.7 on 2021-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0036_auto_20210929_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
