# Generated by Django 3.2.7 on 2021-10-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_core', '0037_movie_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trailer',
        ),
    ]
