# Generated by Django 3.2.7 on 2021-10-21 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_core', '0043_alter_movie_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_later',
            field=models.ManyToManyField(blank=True, editable=False, related_name='watch_later', to=settings.AUTH_USER_MODEL),
        ),
    ]
